source 'https://rubygems.org'

ruby '2.1.5'

gem 'sinatra'
gem 'sinatra-flash'
gem 'sinatra-asset-pipeline'
gem 'haml'
gem 'sass'
gem 'bootstrap-sass'
gem 'thin'

group :test do
  gem 'rspec'
  gem 'capybara'
end
