require 'sinatra/asset_pipeline/task'
require_relative 'app'

Sinatra::AssetPipeline::Task.define! App

desc 'Seed database'
task :seed do
  NVTT::Database.seed
end

if %w{development test}.include? ENV['RACK_ENV']
  require 'rspec/core/rake_task'
  RSpec::Core::RakeTask

  desc 'Default task'
  task :default => :spec.new(:spec)
end

