require 'sinatra/asset_pipeline/task'
require 'rspec/core/rake_task'
require_relative 'app'

Sinatra::AssetPipeline::Task.define! NVTT::App

desc 'Seed database'
task :seed do
  cp 'db/db_seed.json', 'db/db.json'
end


RSpec::Core::RakeTask.new(:spec)

desc 'Default task'
task :default => :spec
