require 'sinatra/asset_pipeline/task'
require 'rspec/core/rake_task'
require_relative 'app'

Sinatra::AssetPipeline::Task.define! App

desc 'Seed database'
task :seed do
  NVTT::Database.seed
end

RSpec::Core::RakeTask.new(:spec)

desc 'Default task'
task :default => :spec
